[main]
pad=2x1
# include=/usr/share/foot/themes/paper-color-light
font=Misc Tamsyn:style=Bold:size=14
font-bold=Misc Tamsyn:style=Bold:size=14
font-italic=Misc Tamsyn:style=Bold:size=14
font-bold-italic=Misc Tamsyn:style=Bold:size=14
[colors]
alpha=0.87
# background=000000
